# Generated by Django 4.1.6 on 2023-02-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comments',
            new_name='comment',
        ),
    ]
